version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./packages/app/Dockerfile
      target: development-stage
      cache_from:
        - matterlabs/local-node:latest
    command: npm run --prefix packages/app dev -- --host
    ports:
      - '3010:3010'
    volumes:
      - ./packages/app:/usr/src/app/packages/app
      - /usr/src/app/packages/app/node_modules
    depends_on:
      - api
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: ./packages/worker/Dockerfile
      target: development-stage
      cache_from:
        - block-explorer_worker:latest
    command: npm run --prefix packages/worker dev:debug
    environment:
      - PORT=3001
      - LOG_LEVEL=verbose
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=block-explorer
      - BLOCKCHAIN_RPC_URL=http://zksync:3050
      - BATCHES_PROCESSING_POLLING_INTERVAL=1000
    ports:
      - '3001:3001'
      - '9229:9229'
      - '9230:9230'
    volumes:
      - ./packages/worker:/usr/src/app/packages/worker
      - /usr/src/app/packages/worker/node_modules
    depends_on:
      zksync:
        condition: service_healthy
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
      target: development-stage
      cache_from:
        - postgres:latest #not sure here about the name
    command: npm run --prefix packages/api dev:debug
    environment:
      - PORT=3020
      - METRICS_PORT=3005
      - LOG_LEVEL=verbose
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/block-explorer
    ports:
      - '3020:3020'
      - '3005:3005'
      - '9231:9229'
      - '9232:9230'
    volumes:
      - ./packages/api:/usr/src/app/packages/api
      - /usr/src/app/packages/api/node_modules
    depends_on:
      - worker
    restart: unless-stopped

volumes:
  geth:
  postgres:
  zksync-config:
  zksync-data:
