name: Documentation build

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build docusaurus docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        working-directory: ./packages/testing-docs
        run: yarn install --frozen-lockfile
      - name: Build website
        working-directory: ./packages/testing-docs
        run: yarn build

