name: Integration test - API

on: pull_request

jobs:
  runTests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    strategy:
      matrix:
        node-version: ['lts/*'] # 18.17.1 or lts/* 
        test-pattern:
          - accounts.test.ts
          # - addresses.test.ts
          # - batches.test.ts
          # - blocks.test.ts
          # - contracts.test.ts
          # - logs.test.ts
          # - stats.test.ts
          # - tokens.test.ts
          # - transactions.test.ts
    name: 'API test set: ${{ matrix.test-pattern}} / Node: ${{ matrix.node-version}}'
    steps:
      - name: Checkout with Submodule
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: docker-compose pull

      - uses: satackey/action-docker-layer-caching@v0.0.11
      
      - name: Start docker containers
        run: |
          docker-compose -f "docker-compose.yaml" up -d --build

      - name: API tests run (parallel)
        working-directory: packages/integration-tests
        run: |
          npm ci --no-audit
          npx playwright install --with-deps chromium
      
      - name: API tests run (parallel)
        working-directory: packages/integration-tests
        run: |
          npx jest
      - name: Stop containers
        if: always()
        run: |
          docker-compose -f "docker-compose.yaml" down
