name: Create Release

on:
  push:
    branches:
      - main
      - '[0-9]+.*'
      - prod

jobs:
  createReleaseVersion:
    name: Create Release Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      releaseVersion: ${{ steps.release.outputs.releaseVersion }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: Lint
        run: |
          npm run lint -- -- --no-fix --max-warnings 0

      - name: Test
        run: |
          npm run test:ci

      - name: App type check
        working-directory: ./packages/app
        run: |
          npm run typecheck

      - name: Create Release Version
        id: release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
            VITE_APP_ENVIRONMENT=production \
              npx semantic-release

  deployBackendToStaging:
    name: Deploy Block Explorer backend to staging
    runs-on: [matterlabs-ci-runner]
    permissions:
      contents: read
    needs: createReleaseVersion
    if: ${{ needs.createReleaseVersion.outputs.releaseVersion != '' }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate build ID for Flux Image Automation
        id: setVersionForFlux
        run: |
          sha=$(git rev-parse --short HEAD)
          ts=$(date +%s%N | cut -b1-13)
          echo "::set-output name=imageTag::${sha}-${ts}"

      - name: Auth to google artifact registry
        run: |
          gcloud auth configure-docker us-docker.pkg.dev -q 

      - name: Build and push Docker image for API
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
              "us-docker.pkg.dev/matterlabs-infra/matterlabs-docker/block-explorer-api:v${{ needs.createReleaseVersion.outputs.releaseVersion }}"
          file: packages/api/Dockerfile
          no-cache: true

      - name: Build and push Docker image for Worker
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
              "us-docker.pkg.dev/matterlabs-infra/matterlabs-docker/block-explorer-worker:v${{ needs.createReleaseVersion.outputs.releaseVersion }}"
          file: packages/worker/Dockerfile
          no-cache: true
